{{- if .Values.bufferServiceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ntail-streams.bufferServiceAccountName" . }}
  labels:
    {{- include "ntail-streams.labels" . | nindent 4 }}
  {{- with .Values.bufferServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
