{{- if .Values.gwServiceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ntail-streams.gwServiceAccountName" . }}
  labels:
    {{- include "ntail-streams.labels" . | nindent 4 }}
  {{- with .Values.gwServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
